### ISSUE TITLE
标点符号的位置（简中习惯）

### ISSUE THREAD

**Issue by RuixiZhang42** [NightFurySL2001/TangYuan-font#1]
首先感谢夜煞之乐、猫啃君用心补字，让广大简体中文用户有优质的圆体可以免费使用！

我注意到「糖圆体」的标点符号是从「jf&nbsp;粉圆」继承而来的，与简中习惯并不相同。具体来说：
- 如下 8 个标点符号需要调整：`、`&nbsp;(U+3001), `。`&nbsp;(U+3002), `！`&nbsp;(U+FF01), `，`&nbsp;(U+FF0C), `．`&nbsp;(U+FF0E), `：`&nbsp;(U+FF1A), `；`&nbsp;(U+FF1B), `？`&nbsp;(U+FF1F)。
- 以及 8 个对应的直排标点：`︐`&nbsp;(U+FE10), `︑`&nbsp;(U+FE11), `︒`&nbsp;(U+FE12), `︓`&nbsp;(U+FE13), `︔`&nbsp;(U+FE14), `︕`&nbsp;(U+FE15), `︖`&nbsp;(U+FE16), 直排实心句点&nbsp;(`uniFF0E.vert`)。

做了一个示意图，希望会有帮助：
![tangyuanpunct](https://user-images.githubusercontent.com/39968857/92037627-11c47900-ed40-11ea-8d1b-2a0d25718896.png)

**Comment by NightFurySL2001** [comment]
您好。

其实我们已经讨论过这个问题，最后因为时间紧凑及不确定性，因此没有调整标点符号的位置。
我们的考虑点在于本字体是基于传承字形（旧字形），因此考虑后决定沿用置中版本，等待使用后的设计师反馈才决定有没有必要修改成左下位置。目前本项目已经加入[待办事项列表](https://github.com/NightFurySL2001/TangYuan-font/blob/master/TO_DO.md)并且已经确认`猫啃网糖圆体`版本将会修改标点符号，可以等待之后的更新消息。（就是因为如此加上未完成GB/T 2312，才标注本版本为测试版）

至于`传承糖圆体`，因为该字体将会继续沿用粉圆的旧字形，因此标点符号我个人是倾向使用横排左下、直排置中。这个还是有待探讨的，将会在后面才觉得最终版如何修改。

**Comment by RuixiZhang42** [comment]
更细致地观察了一下「Kosugi Maru」跟「jf open 粉圓」的区别，发现 justfont 不只调整了位置，还调整了大小、粗细。

![punct-adjust](https://user-images.githubusercontent.com/39968857/92260897-99c49300-eea6-11ea-9fb4-329eafc9c669.png)

比较明显的如下：
1. 「jf open 粉圓」的「句号」调粗了，「逗号」「冒号」「分号」调大了，使得视觉效果更加平衡。
2. 「jf open 粉圓」的「叹号」「问号」调矮了，直排时有更多呼吸空间。
3. 另外，偏靠式的「逗号」跟「点号」，在对齐上有讲究。

**Comment by NightFurySL2001** [comment]
我先这么回复，明天得空了再详细说明：
1. 你的图片有一个比较嗯...有问题的前提：你假设了两个字体的upm是一样，但是实际上两者有差异。没记错小杉是1000，粉圆是1024。

下面方式的前提：我使用fontlab进行编辑，复制粘贴glyph时以上upm问题会自动解决成粉圆的1024upm。
2. 将小杉的字复制过去粉圆进行大小调整后，个人调整后发现参数如下：以中心为主，横向与竖向分别缩小97%后，往下移动30px。所有汉字也是经过同样的transformation。
3. 粉圆加粗了逗句号，但是换回小杉的左下/右上时不需要调整粗细。置中的标点粗细应该会比左下的标点粗一些保持平衡。
4. 左下/右上的标点符号必须符合汉字的baseline，才会显示出跟汉字流畅的标点。
5. jf的设计师有谈到baseline下潜的迹象（无法与他们的金萱系列对齐），未来版本他们可能会再次修改baseline。

其实糖圆体已经替换了4个标点：开关单双引号，是经过缩小+下移的transformation。目前看起来使用上并没有什么问题反馈，因此我觉得是可以直接替换左下/右上标点；冒号跟引号根据逗句号的baseline确定就可以了；问号跟叹号才是棘手的问题，可能会比baseline低/高一些，需要进行排版测试才能决定位置。

P/S: 其实小杉里面有的左下/右上标点我已经制作好patch字体准备覆盖了，但是如上因素没有进行替换。需要的话我可以之后上传这里给你测试看看。
________________________________

**Comment by RuixiZhang42** [comment]
> 1. 你的图片有一个比较嗯...有问题的前提：你假设了两个字体的upm是一样，但是实际上两者有差异。没记错小杉是1000，粉圆是1024。

额，可能是我没表达清楚让您误会了。我贴的图里，小杉、粉圆都是 10&#8239;pt 大小，所以跟 upm 相同与否没有关系。不管是 1&#8239;em=1000&#8239;units 还是 1&#8239;em=1024&#8239;units，如果我调用 10&#8239;pt 的字，那么 1&#8239;em 就会等于 10&#8239;pt。在相同大小的物理尺寸下，粉圆的逗号的确比小杉的逗号大（冒号、分号同理）。

另：从 Google Fonts 上下载的 `KosugiMaru-Regular.ttf`，字体文件内的 upm 是 1024，与粉圆是一样的。您可能是在引用粉圆的这条 issue：https://github.com/justfont/open-huninn-font/issues/22

> 3. 粉圆加粗了逗句号，但是换回小杉的左下/右上时不需要调整粗细。置中的标点粗细应该会比左下的标点粗一些保持平衡。

同意置中的标点可以更粗一些。但如上所述，小杉自带的逗号的确比粉圆的逗号小。不过，既然是「原配」，我个人的审美也只供参考（我认为小杉逗号可以稍微调大一点，跟「原配」的句号会比较搭）。

> 4. 左下/右上的标点符号必须符合汉字的baseline，才会显示出跟汉字流畅的标点。

您可能也误会了我用橙色标出来的部分。

小杉的字身框，横向 0 到 1024，纵向 -123 到 901。它的横排空心句号，左边与下边的 side-bearing 均为 41&#8239;units；直排空心句号，右边与上边的 side-bearing 也均为 41&#8239;units。也就是说，空心句号是在「角落正中」。然而，实心句号虽然也是一个圆，但它并不在角落正中，因为它横排时在左下角但偏上、直排时在右上角但偏右。实心句号是跟逗号的那一点对齐的，所以才不是在角落正中，这是我说的「对齐上有讲究」本意。

> 5. jf的设计师有谈到baseline下潜的迹象（无法与他们的金萱系列对齐），未来版本他们可能会再次修改baseline。

这个就有点迷了，因为金萱的 upm 是 1000，字身框纵向 -120 到 880，跟小杉是一致的。日本字体厂商有比较统一的规格，汉字字身框的底部一般都比西文基线低 12%（1024×12%≈123），而字身框顶部高 88%（1024×88%≈901）。字身框是对齐的，若是「混排看起来仍然baseline下潜」，那应该是字面框或者重心不统一的问题。

**Comment by RuixiZhang42** [comment]
粉圆基线下潜已经报告 https://github.com/justfont/open-huninn-font/issues/28

**Comment by NightFurySL2001** [comment]
>自我P/S: 不要睡前回复Email。

1. 确认记错了，都是1024upm。

2. 如果将小杉的符号直接粘贴过去粉圆，如图示范：
![image](https://user-images.githubusercontent.com/33471049/92304128-ea72e380-efad-11ea-9730-37f99ff496a2.png)
【青色：小杉；蓝色：粉圆】
FontLab里面的转换设置截图：
![image](https://user-images.githubusercontent.com/33471049/92304174-273eda80-efae-11ea-8382-0c8fcb7be788.png)
转换后，再把粉圆粘贴进去的情况：
![image](https://user-images.githubusercontent.com/33471049/92304242-c237b480-efae-11ea-99c6-65dea99297b4.png)
【注意：是小杉圆体全局转换，操作后字符宽度会缩小到993pt，粉圆则是单层在转换后将字符宽度修改为1024。这个部分的详细操作我并不是很清楚。】

3. 视情况吧，粉圆除了置中的标点粗细调整外，其他字符并没有差异。

4. 参考如下：
![image](https://user-images.githubusercontent.com/33471049/92304449-97e6f680-efb0-11ea-80ac-080281a04bdd.png)
我的说明为中文全宽标点符号（。、）是有对齐汉字的基线，西文全宽标点（．，）则是另外对齐一条偏上、视觉上同高的基线。（：；）也会需要对应西文全宽标点（．，）的位置。直排时，则是一律右对齐。

5. 该问题是我在与 justfont 的设计师请教时他们说出的问题。我的推断是：因为 (2) 提到的字面缩小94% (97% × 97%)，虽然计算上比例仍旧保持88:12，但是与西文匹配就会看起来偏高，因此设计师决定往下移动30px以对齐西文。我觉得可能可以修改为往下移动12pt而不是30pt。（这个并不在讨论范围内）

----
示例标点符号覆盖字体：
[huninn-punc.zip](https://github.com/NightFurySL2001/TangYuan-font/files/5178009/huninn-punc.zip)

**Comment by RuixiZhang42** [comment]
哇！速度好快！

> 4. 我的说明为中文全宽标点符号（。、）是有对齐汉字的基线，西文全宽标点（．，）则是另外对齐一条偏上、视觉上同高的基线。[……] 直排时，则是一律右对齐。

原来您说的「汉字基线」是指「字面框的基线」，而我说的则是「字身框的基线」，不过对于视觉对齐的理解是一致的！

横排时感觉还行，就是逗号有点小（跟空心句号相比，而且还被缩小了97%）……直排一律右对齐的话，感觉有点太偏右了，可以试试（．，）稍微调左一点点，跟（。、）视觉上同右吗？当然，还是得看长文排版的效果，由两位设计师决定。

> 5. 该问题是我在与 justfont 的设计师请教时他们说出的问题。我的推断是：因为 (2) 提到的字面缩小94% (97% × 97%)，虽然计算上比例仍旧保持88:12，但是与西文匹配就会看起来偏高，因此设计师决定往下移动30px以对齐西文。

的确很有可能是西文匹配的原因，汉字被调小、调低了。粉圆调完之后，字身框就变成85:15，而不再是88:12了，下潜3%，怪不得明显不匹配金萱。

**Comment by NightFurySL2001** [comment]
> 就是逗号有点小

看排版效果后会再修改：粉圆的标点也是缩小97%，只是加粗了一些。附注的字体文件则是从小杉圆体直接复制缩小移下的。

> 直排一律右对齐的话，感觉有点太偏右了

同上。

----

另外一个问题：`传承糖圆体`的标点符号可能修改成横排左下、直排置中（两个版本都会通过OpenType `cpct` 提供），而引号修改成同样外观的形状（如下）。你会觉得适合吗？
![image](https://user-images.githubusercontent.com/33471049/92327990-2e3e1980-f090-11ea-9050-f59b98d760f0.png)

**Comment by RuixiZhang42** [comment]
> `传承糖圆体`的标点符号可能修改成横排左下、直排置中

因为是「传承」字型，这样的直排标点设置也不错。是不是可以大致理解为`传承糖圆体`的横排从简中横排，而直排从繁中直排？

> 而引号修改成同样外观的形状

我并没有见过图中直排引号的形态、位置，手边也没有出版物可以参考。感觉这种用法很罕见，也不好说合不合适。（思源系列的简中，采用的方案是替换`U+201C -> U+FE43`、`U+201D -> U+FE44`等等）

**Comment by NightFurySL2001** [comment]
> `传承糖圆体`的横排从简中横排，而直排从繁中直排？

对的，可以这样理解。


引号可参考繁体字体：
![image](https://user-images.githubusercontent.com/33471049/92576124-b81dfa80-f2bb-11ea-84fb-3d2bb93e3e1d.png)

**Comment by NightFurySL2001** [comment]
@RuixiZhang42 问题已经解决（虽然还不是最佳状态）。参见 v0.11beta。
