### ISSUE TITLE
建议猫啃网糖圆体的英文及数字部分对Il1Oo0进行区分

### ISSUE THREAD

**Issue by admin05** [NightFurySL2001/TangYuan-font#3]
目前猫啃网糖圆体对o0OiI等数字和字母容易混淆，建议参考Jetbrains Mono等字体，对上述字体进行区分，使得编程时更易读

**Comment by NightFurySL2001** [comment]
本字体并不是主打编程字体，如果要编程使用可以自行替换西文部分。
